"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var article_1 = require("./article/article");
exports.Article = article_1.Article;
exports.GroupeArticles = article_1.GroupeArticles;
exports.QteArticles = article_1.QteArticles;
exports.BaseArticle = article_1.BaseArticle;
var document_1 = require("./document/document");
exports.Document = document_1.Document;
exports.Facture = document_1.Facture;
exports.FactureAcompte = document_1.FactureAcompte;
exports.Devis = document_1.Devis;
exports.DetailsTVA = document_1.DetailsTVA;
var logo_1 = require("./logo/logo");
exports.Logo = logo_1.Logo;
var reglement_1 = require("./reglement/reglement");
exports.Reglement = reglement_1.Reglement;
var vente_1 = require("./vente/vente");
exports.Vente = vente_1.Vente;
